- name: Find number of requests
  community.general.read_csv:
    path: "{{ '/tmp/hyperfoil/workspace/run/' + test_runid + '/stats/total.csv' }}"
    key: Phase
  register: test_requests
- name: Print number of requests
  debug:
    msg: "{{ item }} = {{ test_requests.dict[item].Requests }}"
  loop: "{{ test_requests.dict.keys()|list }}"
- name: Download JFR
  ansible.builtin.fetch:
    src: "{{ hyperfoil_dir }}/hfc-{{ ansible_hostname }}.jfr"
    dest: "./"
    flat: true
  when: hyperfoil_jfr
