- name: Check for hyperfoil_log_config
  when: hyperfoil_log_config is defined
  fail:
    msg: "Use controller_log_config instead of hyperfoil_log_config"
- when: controller_log_config is defined
  block:
  - name: Upload log config file
    ansible.builtin.copy:
      src: "{{ controller_log_config }}"
      dest: "{{ hyperfoil_dir }}"
  - ansible.builtin.set_fact:
      hyperfoil_log_config: "{{ hyperfoil_dir }}/{{ controller_log_config | basename }}"

- name: Setup Hyperfoil controller
  ansible.builtin.import_role:
    name: hyperfoil.hyperfoil_setup
