# Creates a named SSH key at $HOME/.ssh on the controller if not present
ssh_key: "{{ undef() }}"
# Allows downloading benchmark result when stats are retrieved for a given run
download_results: false
# Allows to provide a local log file to be used by the controller
# Use this instead of hyperfoil_log_config
controller_log_config: "{{ undef() }}"

# All of these are described at https://github.com/Hyperfoil/hyperfoil_setup

hyperfoil_distribution: "{{ undef() }}"
hyperfoil_version: "{{ undef() }}"
hyperfoil_dir: "{{ undef() }}"
hyperfoil_controller_group: hyperfoil_controller
hyperfoil_controller_port: "{{ undef() }}"
hyperfoil_controller_start_timeout: "{{ undef() }}"
hyperfoil_controller_args: "{{ undef() }}"
hyperfoil_trigger_url: "{{ undef() }}"
# DO NOT USE, instead use controller_log_config
hyperfoil_log_config: "{{ undef() }}"
hyperfoil_jfr: false
hyperfoil_controller_debug_port: "{{ undef() }}"
hyperfoil_controller_debug_suspend: n
hyperfoil_agent_debug_port: "{{ undef() }}"
libperfjava: "{{ undef() }}"

