# Location of the cache configuration to use for the named cache
cache_file: files/cache.xml
# Optional way to override the server image used by the benchmar
server_image: quay.io/infinispan/server
# Java VM arguments passed to the server image when running
server_java_args: "{{ undef() }}"
# Allows for automatic generation of Java Flight Recorder and download
# This will append to the server_java_args if provided
capture_jfr: false
# Location of a server configuration file that the server starts with
# This can be used to change this with the cache manager itself such as authencation mechs
server_configuration_file: "{{ undef() }}"
# Location of where Infinispan Server benchmark related files will be created
# Normally this is not needed to be changed
server_tmp_dir: /tmp/infinispan-benchmark
