    - name: Enable JFR
      set_fact:
        # TODO: change this to allow overriding in case if java_options is defined as inventory
        java_options: "{{ '-XX:StartFlightRecording:filename=' + server_tmp_dir + '/jfr/server-' + inventory_hostname + '.jfr' }}"
      when: capture_jfr is defined and capture_jfr

    - name: Apply server_java_args
      set_fact:
        java_options: "{{ java_options + server_java_args if java_options is defined else server_java_args }}"
      when: server_java_args is defined

    - name: Copy Infinispan Server file if present
      ansible.builtin.copy:
        src: "{{ server_configuration_file }}"
        dest: "{{ server_tmp_dir }}"
      when: server_configuration_file is defined

    - name: Start Infinispan container
      containers.podman.podman_container:
        name: infinispan-server
        image: "{{ server_image }}"
        recreate: true
        state: started
        net: host
          #command: ./bin/launch.sh #-Dinfinispan.cluster.stack=kubernetes -Djgroups.dns.query="infinispan-dns-ping.myproject.svc.cluster.local" 
          #workdir: /opt/infinispan
        env:
          USER: "{{ user }}"
          PASS: "{{ pass }}"
            #Not needed with net host as this is required for jgroups
            #ports:
            #- 11222:11222
          JAVA_OPTIONS: "{{ java_options | default('') }}"
        volume:
          - "{{ server_tmp_dir }}:{{ server_tmp_dir }}"
        command:
          - "{{ '-c ' + server_tmp_dir + '/' + server_configuration_file | basename if server_configuration_file is defined else '' }}"

    - name: Wait until server is up or print log
      block:
        - name: Wait for port 11222 to become open on the host, don't start checking for 10 seconds
          ansible.builtin.wait_for:
            host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
            port: 11222
            delay: 10
            timeout: 60
      rescue:
        - name: Collect container log
          ansible.builtin.command: podman container logs infinispan-server
          register: container_log
        - name: Print container log
          ansible.builtin.fail:
            msg: "{{ container_log.stdout_lines }}"

    - name: Print contents of cache_file
      ansible.builtin.debug:
        msg: "the value of {{ cache_file }} is {{ lookup('ansible.builtin.file', cache_file) }}"
      run_once: true

