cluster_identifier: "{{ lookup('env', 'USER') }}"
cluster_name: "benchmark_{{ cluster_identifier }}"

cidr_ip: "{{ control_host_ip.stdout }}/32"

server_cluster_size: 3
server_instance_type: t2.micro
# Ubuntu
server_ami_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240207.1
# Needs to match the user created by AMI
server_user: ubuntu

agent_cluster_size: 2
agent_instance_type: t2.micro
#  Amazon Linux
#agent_ami_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240207.1
agent_ami_name: al2023-ami-2023.3.20240304.0-kernel-6.1-x86_64
# Needs to match the user created by AMI
#agent_user: ubuntu
agent_user: ec2-user


# Controller only supports 1, so this cannot be changed
controller_cluster_size: 1
controller_instance_type: t2.micro
#  Amazon Linux
#controller_ami_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240207.1
controller_ami_name: al2023-ami-2023.3.20240304.0-kernel-6.1-x86_64
# Needs to match the user created by AMI
#controller_user: ubuntu
controller_user: ec2-user

no_log_sensitive: true
