cluster_identifier: "{{ lookup('env', 'USER') }}"
cluster_name: "benchmark_{{ cluster_identifier }}"

cidr_ip: "{{ control_host_ip.stdout }}/32"

# Utilize Graviton instances.
# The `*_user` in each section must match the AMI user (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/managing-users.html#ami-default-user-names)
# To list the available AMI names, select the desired region at the last argument:
# aws ec2 describe-images --owners self amazon --filters "Name=architecture,Values=arm64" "Name=virtualization-type,Values=hvm" --region sa-east-1

server_cluster_size: 3
server_instance_type: t4g.small
server_ami_name: debian-12-arm64-20231013-1532
server_user: admin
server_volume_name: /dev/xvda
# Allows overriding the size of the volume used by the server image
server_volume_size: 20

# Hyperfoil agents.
# These instances are responsible to drive the load.
agent_cluster_size: 2
agent_instance_type: t4g.micro
agent_ami_name: al2023-ami-2023.4.20240513.0-kernel-6.1-arm64
agent_user: ec2-user
agent_volume_name: "/dev/xvda"
agent_volume_size: "8"

# Hyperfoil controller.
# Controller only supports 1 instance, so this cannot be changed.
# The insntance only summarizes the statistics and coordinate the agents, we can use a smaller instance.
controller_cluster_size: 1
controller_instance_type: t4g.micro
controller_ami_name: al2023-ami-2023.4.20240513.0-kernel-6.1-arm64
controller_user: ec2-user
controller_volume_name: "/dev/xvda"
controller_volume_size: "8"

no_log_sensitive: true
