# Start or Stop Instances
- name: "{{ operation[0]|upper }}{{ operation[1:] }} Instances"
  amazon.aws.ec2_instance:
    state: '{{ "stopped" if operation == "stop" else "started" }}'
    region: '{{ region }}'
    filters:
      "tag:Name": '*{{ cluster_name }}'
      instance-state-name: ['running', 'stopped', 'stopping']
  no_log: "{{ no_log_sensitive }}"

## Need to loop over server, controller and agent and have an array for them
- when: operation == "start"
  block:
  # When starting instances via `ec2_instance` module sometimes the `public_ip_address` is missing in the result.
  # Added additional `ec2_instance_info` step to work around the issue.
    - name: Get Instance Information
      amazon.aws.ec2_instance_info:
        region: '{{ region }}'
        filters:
          "tag:Name": '*{{ cluster_name }}'
          instance-state-name: ['running']
      register: instance_info
      no_log: "{{ no_log_sensitive }}"
    - name: Flatten instances
      include_tasks: flat-map-instances.yml
      loop: [ 'server', 'agent', 'controller' ]
      loop_control:
        loop_var: instance_type
    - name: Create Inventory File
      template:
        src: inventory.yaml.j2
        dest: '{{ cluster_name }}_{{ region }}_inventory.yaml'
